export const GET_ARTICLES = "GET_ARTICLES";
export const GET_TAGS = "GET_TAGS";
export const SET_USER = "SET_USER";
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const GET_SINGLE_ARTICLE = "GET_SINGLE_ARTICLE";
export const GET_SINGLE_ARTICLE_COMMENTS = "GET_SINGLE_ARTICLE_COMMENTS";
export const IS_USER_LOGGEDIN = "IS_USER_LOGGEDIN";
